Real-Time-Chat/RealTimeChat/Models/ErrorViewModel.cs
namespace RealTimeChat.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Real-Time-Chat/RealTimeChat/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealTimeChat.DB.EF;
using RealTimeChat.DB.EF.Entities;
using RealTimeChat.DTO;

namespace RealTimeChat.Controllers
{
    public class ChatController : Controller
    {
        private readonly ILogger<ChatController> _logger;
        private readonly RealTimeChatDbContext _context;

        public ChatController(ILogger<ChatController> logger, RealTimeChatDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Chat/GetLastTenRecords")]
        public async Task<IActionResult> GetLastTenRecords()
        {
            var records = await _context.Messages
                .OrderBy(m => m.CreatedAt)
                .Take(10)
                .Include(m => m.User)
                .Select(m => new
                {
                    userName = m.User.UserName,
                    message = m.MessageText
                })
                .ToListAsync();

            if (!records.Any())
            {
                return NoContent();
            }

            return Ok(records);
        }

        [HttpPost("Chat/AddMessage")]
        public async Task<IActionResult> AddMessage([FromBody] MessageDto messageDto)
        {
            var user = _context.Users.FirstOrDefault(u => u.UserName == messageDto.UserName);

            if (user == null)
            {
                user = new User { UserName = messageDto.UserName };
                _context.Users.Add(user);
                await _context.SaveChangesAsync();
            }

            var message = new Message
            {
                MessageText = messageDto.Message,
                UserId = user.UserId,
                CreatedAt = DateTime.Now
            };

            _context.Messages.Add(message);
            await _context.SaveChangesAsync();

            return Ok(new { Success = true });
        }
    }
}

Real-Time-Chat/RealTimeChat/Views/Chat/Index.cshtml
@{
    ViewData["Title"] = "Real-time Chat";
}

<div class="container">
    <div class="row p-1">
        <div class="col-1">Name</div>
        <div class="col-5"><input type="text" id="userNameInput" /></div>
    </div>
    <div class="row p-1">
        <div class="col-1">Message</div>
        <div class="col-5"><input type="text" class="w-100" id="messageInput" /></div>
    </div>
    <div class="row p-1">
        <div class="col-6 text-end">
            <input type="button" id="sendButton" value="Send Message" />
        </div>
    </div>
    <div class="row p-1">
        <div class="col-6">
            <hr />
        </div>
    </div>
    <div class="row p-1">
        <div class="col-6">
            <ul id="messagesList"></ul>
        </div>
    </div>
</div>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/realtimechatscript.js"></script>

Real-Time-Chat/RealTimeChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Real-Time Chat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RealTimeChat.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Chat" asp-action="Index">Real-time chat</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RealTimeChat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>